apiVersion: v1
kind: ConfigMap
metadata:
    name: nshards
data:
    NSHARDS: "1"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logdevice
spec:
  serviceName: "logdevice"
  replicas: 3
  selector:
    matchLabels:
      app: logdevice
  template:
    metadata:
      labels:
        app: logdevice
    spec:
      containers:
      - name: logdevice
        image: "facebookincubator/logdevice"
        command:
          - "/usr/local/bin/logdeviced"
          - "--config-path"
          - "/etc/logdevice/config.json"
          - "--address"
          - "$(POD_IP)"
          - "--name"
          - "$(POD_NAME)"
          - "--local-log-store-path"
          - "/data/logdevice"
        ports:
        - containerPort: 4440
        - containerPort: 4441
        - containerPort: 5440
        - containerPort: 6440
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
        - name: shard0
          mountPath: /data/logdevice/shard0
        - name: config
          mountPath: /etc/logdevice
        - name: nshards
          mountPath: /data/logdevice
      volumes:
      - name: config
        configMap:
          name: logdevice-config
          items:
            - key: config.json
              path: config.json
      - name: nshards
        configMap:
          name: nshards
          items:
            - key: NSHARDS
              path: NSHARDS
  volumeClaimTemplates:
  - metadata:
      name: shard0
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "do-block-storage"
      resources:
        requests:
          storage: 50Gi
